### ISSUE TITLE
Nova 1 Bio layout fix?

### ISSUE THREAD

**Issue by Lostboy747** [mooeypoo/Nova2-Mod--Crew-Bio-Page#1]
Is there any way to adapt this for those sites using the Nova 1 bio(old bio) for certain skins?

**Comment by mooeypoo** [comment]
What do you mean? Are you using Nova1? The controller wouldn't work for Nova1, bt if it's only about the skin, you can go into the view file and take just the award piece, then stick it into wherever you want it in your view.

Does this help?

**Comment by Lostboy747** [comment]
No, I'm using Nova 2, but I downloaded the Nova 1 Character Bio Page from the Mods from http://xtras.anodyne-productions.com/index.php/nova2. My players prefer that layout for our other skins.

**Comment by mooeypoo** [comment]
Ah, I made a fix for the narrow page, I'll work on a fix for the second one too.

**Comment by mooeypoo** [comment]
Alright, I added that page to the views. Just rename it to remove the -old-char-bio (so, it will now be personnel_character.php) and upload it to the same view location on your server.

This should work. Please let me know if there are any problems with it!
